package multipletimepad;

import java.util.Comparator;
import java.util.HashMap;


public class CharProbability {
	private static HashMap<Character, Integer> countOfChar;
	private static HashMap<String, Integer> countOfString;
	private static int totalCount;
	
	public static float getProbabilityOfChar(char key) {
		initIfNecessary();
		
		return 1f * countOfChar.getOrDefault(key, 0) / totalCount;
	}
	
	public static float getProbabilityOfString(String key) {
		initIfNecessary();
		
		if(countOfString.containsKey(key)) {
			// Nothing to do here
		} else {
		}
			
		return countOfString.get(key);
	}
	
	
	private static void initIfNecessary() {
		if (countOfChar == null) {
			System.out.printf("Scanning data with %d characters.%n", data.length());
			
			countOfChar = new HashMap<>(PossibleChars.count());
			totalCount = 0;
			
			// I am using a stream here, since toCharArray would copy the String
			data.chars().forEach((currentCharAsInt) -> {
				char c = (char) currentCharAsInt;
				int oldCount = countOfChar.getOrDefault(c, 0);
				countOfChar.put(c, oldCount + 1);
				totalCount++;
				}
			);
		}
	}

	// Source: https://legal-dictionary.thefreedictionary.com/English+Law, 31741 chars
	private static final String data = "English Law\r\n" + 
			"Also found in: Wikipedia.\r\n" + 
			"English Law\r\n" + 
			"The system of law that has developed in England from approximately 1066 to the present.\r\n" + 
			"The body of English law includes legislation, Common Law, and a host of other legal norms established by Parliament, the Crown, and the judiciary. It is the fountain from which flowed nearly every facet of U.S. law during the eighteenth and nineteenth centuries.\r\n" + 
			"Many of the concepts embodied in the U.S. Constitution—such as the separation and delegation of powers between three branches of government and the creation of an elective national assembly representing the will of the people—trace their roots to English law. Fundamental legal procedures applied in the U.S. civil and criminal justice systems also originated in England. The jury system, for example, slowly matured into its modern form over several hundred years of English history. The antecedents of many substantive areas of U.S. law, including the ubiquitous system of state and federal taxation, may be found in English history as well.\r\n" + 
			"The story of English Constitutional Law prior to the American Revolution, which is inextricably intertwined with the development of English law as a whole during this period, can be told in three parts: the centralization of power in the monarchy, the creation of Parliament as a limitation on the absolute power asserted by the monarchy, and the struggle for supremacy between Parliament and the monarchy. In large part, the American Revolution resulted from Parliament's failure to check the monarchy's sovereignty and establish itself as the supreme lawmaking body representing the people of England and its colonies.\r\n" + 
			"When William, duke of Normandy, also known as William the Conqueror, vanquished England in 1066, there was no English law as the Americans of 1776 came to know it. No national or federal legal machinery had yet been contemplated. Law was a loose collection of decentralized customs, traditions, and rules followed by the Anglians and Saxons, among others. Criminal cases were indistinguishable from civil cases, and both secular and spiritual disputes were resolved at the local level by community courts. Trials in the modern sense did not exist, nor did juries. Guilt and innocence were determined by compurgation and ordeal.\r\n" + 
			"Compurgation was a ritualistic procedure in which accused persons might clear themselves of an alleged wrongdoing by taking a sworn oath denying the claim made against them, and corroborating the denial by the sworn oaths of 12 other persons, usually neighbors or relatives. If an accused person failed to provide the requisite number of compurgators, he or she lost. The number of compurgators was the same as the number of jurors later impaneled to hear criminal cases under the common law. In the United States, the Sixth Amendment to the Constitution required that all criminal trials be prosecuted before 12 jurors—until 1970, when the Supreme Court ruled that six-person juries were permissible (Williams v. Florida, 399 U.S. 78, 90 S. Ct. 1893, 26 L. Ed. 2d 446).\r\n" + 
			"Trial by ordeal was a superstitious procedure administered by clerics who subjected accused persons to physical torment in hopes of uncovering divine signs of guilt or innocence. The most common forms of ordeal involved boiling or freezing waters and hot irons. In the ordeal of freezing water, accused persons were thrown into a pool to see if they would sink or float. If they sank, the cleric believed they were innocent, because the water would presumably reject someone with an impure soul. Of course, persons who sank to the bottom and drowned during this ordeal were both exonerated of their alleged misbehavior, and dead.Battle was another form of primitive trial that was thought to involve divine intervention on behalf of the righteous party. The combatants were armed with long staffs and leather shields, and fought savagely until one party cried, \"Craven,\" or died.\r\n" + 
			"Trial by battle, though in many ways as barbaric as trial by ordeal, foreshadowed modern trials in several ways. The combatants fought in an adversarial arena before robed judges who presided over the battle. The accused person was required to put on a defense, quite literally in the physical sense, against an opponent who was trying to prove the veracity of his or her claims. Some parties to a battle, particularly women, children, and older individuals, were entitled to hire stronger, more able champions to fight on their behalf. This last practice sheds light on the more recent phrase hired guns, which is sometimes used to describe U.S. trial attorneys.\r\n" + 
			"Dr. Bonham's Case\r\n" + 
			"Dr. Bonham's Case, 8 Co. Rep. 114 (Court of Common Pleas [1610]), stands for the principle that legislation passed by the English Parliament is sub-ordinate to the common-law decisions made by trial and appellate court judges, and any statute that is contrary to \"common right and reason\" must be declared void (Thorne 1938).\r\n" + 
			"The decision in this case, which was written by Sir Edward Coke sitting as chief justice for the Court of Common Pleas in England, spawned the concept of Judicial Review under which courts of law, as the primary oracles of the Common Law in the British and U.S. systems of justice, are authorized to invalidate laws enacted by the executive and legislative branches of government. The power of judicial review, which was first recognized by the U.S. Supreme Court in marbury v. madison, 5 U.S. (1 Cranch) 137, 2 L. Ed. 60, is invoked by courts every day across the United States but has since been rendered obsolete in England.\r\n" + 
			"Bonham's Case arose from a dispute regarding the unlicensed practice of medicine. Dr. Thomas Bonham had received a degree in physic medicine from the University of Cambridge. In 1606, Bonham was discovered practicing such medicine in London without a license, and was summoned to appear before the censors at the London College of Physicians, who maintained jurisdiction in that city over the practice of medicine.\r\n" + 
			"Bonham was examined by the college censors in a number of areas regarding his professional practice, and provided answers \"less aptly and insufficiently in the art of physic\" (Stoner 1992, 49). As a result, Bonham was determined unfit to practice medicine in this field, and was ordered to desist from such practice in London. When Bonham was later discovered flouting this order, he was arrested and placed in the custody of the censors.\r\n" + 
			"Bonham refused to undergo further examination. As a graduate of Cambridge, he asserted that the London College of Physicians had no jurisdiction over him and thus possessed no authority to arrest or fine him. Promising to continue his practice of physic medicine if released, Bonham was immediately jailed.\r\n" + 
			"The case came before the Court of Common Pleas when Bonham claimed that his continued detention by the college amounted to False Imprisonment. As a defense, the college relied on its statute of incorporation, which authorized it to regulate all physicians in London and to punish practitioners not licensed by the college. The statute also entitled the college to one-half of all the fines imposed by it.\r\n" + 
			"The Honorable Justice Coke, also a Cambridge graduate, sided with his fellow alumnus. After singing the praises of their alma mater, Coke argued that because the college censors were entitled to receive a portion of the fine they imposed on Bonham, the statute made them prosecutor, plaintiff, and judge in the dispute: \"The censors cannot be judges, ministers and parties; judges … give sentence or judgment; ministers … make summons; and parties … have moiety [half] of the Forfeiture, because no person may be a judge in his own cause … and one cannot be judge and attorney for any of the parties.\" Coke suggested that the impartiality of a judge is compromised when the judge is also the plaintiff who will benefit financially from any fines imposed on the defendant, or the prosecutor who is the advocate responsible for seeking such fines. Although the parliamentary statute in question clearly contemplated that London College would wear all three of these hats, Coke observed,\r\n" + 
			" [I]t appears in our books, that in many cases, the common law will controul Acts of Parliament, and sometimes adjudge them to be utterly void: for when an Act of Parliament is against common right and reason, or repugnant, or impossible to be performed, the common law will controul it, and adjudge such Act to be void.\r\n" + 
			"Coke placed the judiciary in the middle of what was becoming a titanic struggle for power between Parliament and the ruler of England. Until the seventeenth century, the English monarchy enjoyed nearly absolute power over all political and legal matters that concerned the country as a whole. Despite the growing popularity and importance of Parliament during the fifteenth and sixteenth centuries, the monarchy's autocratic power, which King James I (1603–25) asserted was divine in origin, included the prerogative to enact laws without parliamentary consent.\r\n" + 
			"By the close of the seventeenth century, however, the pendulum of power had swung in favor of Parliament. The Glorious Revolution of 1688 subordinated the power of the English Crown and judiciary to parliamentary sovereignty. In 1765, English jurist Sir William Blackstone described \"the power of Parliament\" to make laws in England as \"absolute,\" \"despotic,\" and \"without control.\"The American Revolution, which began eleven years after Blackstone's pronouncement of Parliament's unfettered power, was commenced in response to the coercive legislation passed in the colonies by what had become a despotic Parliament. Thomas Jefferson, James Madison, and their contemporaries believed that a legislative despot was no better than a monarchical despot. In 1787, the U.S. Constitution established the judiciary as a check on the legislative and executive branches of government, a check that was foreshadowed by Coke's opinion in Bonham's Case.\r\n" + 
			"James I was cognizant of the dangers Bonham's Case presented to his claims of divine royal prerogative. The king understood that the \"common law,\" which Bonham's Case said controlled acts of Parliament, was really just a decision made by a court of law, or, more particularly, by a judge or panel of judges. James also understood that if the judiciary were allowed to assert the power to review acts of Parliament, it was only a short step away from passing judgment on actions taken by the Crown.\r\n" + 
			"Accordingly, King James removed Coke from the Court of Common Pleas in 1613, appointing him chief justice of the King's Bench. This constituted a promotion in name only, since Coke was now under closer scrutiny by the Crown.\r\n" + 
			"Much to the Crown's chagrin, Coke's replacement on the Court of Common Pleas, Sir Henry Hobart, expanded the concept of judicial review intimated by Bonham's Case. In Day v. Savadge, Hob. 84 (K.B. 1614), Hobart declared that \"an act of parliament made against natural Equity, as to make a man judge in his own cause, is void in itself\" (as quoted in American General Insurance Co. v. FTC, 589 F.2d 462 [9th Cir. 1979]). Where did the new chief justice derive the court's power to invalidate the laws of Parliament? Hobart said, \"[B]y that liberty and authority that judges have over laws, especially … statute laws, according to reason and best convenience, to mould them to the truest and best use\" (Sheffield v. Ratcliff, Hob. (K.B. 1615), as quoted in Plucknett 1926, 50).\r\n" + 
			"Exasperated by such further attempts to limit his prerogative, James I dismissed Coke from the King's Bench, and ordered him to \"correct\" his decision in Bonham's Case, which had subsequently been published in England's case law reporter known as The Reports. Coke refused to accede to the king's demands.\r\n" + 
			"The importance of Coke's opinion in Bonham's Case is sometimes downplayed by some scholars who point to England's later recognition of Parliament as the country's supreme sovereign entity. However, this criticism overlooks the indelible imprint left by Bonham's Case on U.S. law.\r\n" + 
			"The American colonists were intimately familiar with the writings of Lord Coke. Coke's Reports first came to America on the Mayflower, and the Massachusetts General Court ordered two complete sets from England in 1647. Coke's opinion in Bonham's Case was among his most popular writings.\r\n" + 
			"In Paxton's Case of the Writ of Assistance, Quincy 51 (Mass. 1761), colonist James Otis challenged Massachusetts's authority to issue writs of assistance, general search warrants that empowered local sheriffs to enter private homes and businesses to seize smuggled goods. Otis told the colonial court that he objected to such writs, which were created by a parliamentary act in 1662, because they violated the principle of Bonham's Case: \"As to acts of parliament, an act against the Constitution is void. An act against natural equity is void; and if an act of parliament should be made in the very words of this petition, it would be void. The Executive Courts must pass such acts into disuse.\"John Adams, who was in the Boston courtroom where Otis made his argument for the colonial application of Bonham's Case, later exclaimed, \"Then and there the child Independence was born.\" Adams might also have exclaimed that the seeds of judicial review had been planted in the American colonies by Otis, who was unequivocally assigning to \"Executive Courts\" the responsibility of invalidating parliamentary legislation that violated constitutional precepts.\r\n" + 
			"Four years later, the colonies again relied on the principle of Bonham's Case, this time in their opposition to the Stamp Act, a parliamentary statute that taxed everything from newspapers to playing cards. Thomas Hutchinson, lieutenant governor of Massachusetts, encouraged the \"friends of liberty\" and opponents of the Stamp Act to \"take advantage of the Maxim they find in Lord Coke that an act of parliament against Magna Carta or the peculiar rights of Englishmen is ipso facto void.\"In 1786, the Superior Court of Rhode Island relied on Bonham's Case to strike down a statute that denied the right to trial by jury for certain crimes, because \"Lord Coke\" held that such statutes were \"repugnant and impossible\" (Trevett v. Weeden [Newport Super. Ct. Judicature], as quoted in Plucknett 1926, 66).\r\n" + 
			"The U.S. acceptance of the legal principles enunciated in Bonham's Case culminated in 1803 when the U.S. Supreme Court handed down its decision in Marbury, which established the power of judicial review by authorizing federal judges to invalidate unconstitutional laws enacted by the coordinate branches of government. Nowhere in Marbury does the Supreme Court cite Bonham's Case or expressly quote Lord Coke. But the influence of both Coke and his opinion cannot be missed.\r\n" + 
			"Chief Justice John Marshall, writing for a unanimous Court, began his opinion in Marbury with two premises: the \"constitution controls any legislative act repugnant to it,\" and \"an act of the legislature repugnant to the constitution is void.\" Congress cannot be entrusted to determine the constitutionality of legislation passed by the House and Senate, Marshall implied, for the same reason the London College censors could not be allowed to judge their own cause.\r\n" + 
			"\"To what purpose are the powers [of Congress] limited\" by the federal Constitution, Marshall asked, \"if these limits may, at any time, be passed by those intended to be restrained?\" In a passage that harkens back to Chief Justice Hobart's opinion in Sheffield v. Ratcliff, Marshall concluded that only the judicial branch of government can be entrusted with such an overreaching power: \"It is emphatically the duty of the judicial department to say what the law is. Those who apply the rule to particular cases, must of necessity expound and interpret the rule. If two laws conflict with each other, the court must decide on the operation of each.\"Although Chief Justice Marshall's opinion in Marbury extended to the United States the principles of judicial review first intimated in Bonham's Case, judges, lawyers, and laypersons still debate the legitimacy of allowing unelected (appointed) judges to invalidate legislation enacted by representative institutions in a democratic country.\r\n" + 
			"Further readings\r\n" + 
			"Edwards, R.A. 1996. \"Bonham's Case: The Ghost in the Constitutional Machine.\" Denning Law Journal (annual): 63–90.\r\n" + 
			"William the Conqueror understood the importance of revenue, and that is where he began building the English empire. In 1086, William initiated the Domesday Survey, which sought to determine the amount and value of property held in England, for the purpose of assessing taxes against the owners. The Domesday Survey was conducted by eight panels of royal commissioners who traveled to every county in the country, where they collected information through sworn inquests. Although the survey began as a method of recording real property held in the kingdom, one contemporary Saxon chronicler moaned \"that there was not a single hide … nor … ox, cow or swine\" omitted (Trevelyan 1982). The Court of Exchequer served as auditor, accountant, and tax collector for William, and provided a venue to settle disputes between the Crown and taxpayers, becoming the earliest department of state.\r\n" + 
			"William's system for revenue collection began a process that gradually replaced the community courts of justice with a legal system that emanated from a central location, the king's castle in Westminster. One symbol of powerful centralized government in the United States is the Internal Revenue Service. For many U.S. citizens, paying taxes is a necessary evil. Taxes are necessary to keep the government, and its justice system, afloat. At the same time, they take away individuals' money.\r\n" + 
			"henry ii (1154–89) further strengthened the central government by enlarging the power and jurisdiction of the royal system of justice. During his reign, any crime that breached the ruler's peace was tried before a royal court sitting in Westminster, or by royal itinerant justices who traveled to localities throughout England to hear disputes. Heretofore, the royal court heard only cases that directly threatened the monarch's physical or economic interests. Most other complaints, except for those heard by the Catholic Church, were leveled by private individuals, who were also responsible for proving their accusations. By increasing the sphere of what the government considered public wrongs, Henry II laid the groundwork for the modern U.S. criminal justice system, where attorneys for the federal, state, and local governments are invested with the authority to prosecute persons accused of criminal wrongdoing.Henry II also laid the groundwork for the common-law method of deciding cases, whereby judges make decisions in accordance with other decisions they have rendered in similar matters. The royal system of justice was governed by a single set of legal rules and principles, which was applied evenhandedly to litigants presenting claims to the monarch's justices. This system superseded one that applied the often inconsistent customary laws of neighboring communities of different ethnic backgrounds. Because the monarch's law was applied in a uniform manner, it became \"common\" to every shire in the land. This \"common-law\" system of adjudication was adopted by the American colonies and continues to be applied in nearly all of the 50 states of the Union.\r\n" + 
			"In addition to becoming more prevalent, the royal system of justice was becoming more popular. Its popularity stemmed from the rational legal procedures and reliable modes of evidence developed by the King's Court, which slowly supplanted their superstitious, ritualistic, and dangerous predecessors, compurgation, ordeal, and battle. One new rational procedure was trial by jury, which Henry II made available in land disputes between laypersons and the clergy. The juries comprised 12 sworn men who possessed some knowledge of the property dispute, and were asked to announce a verdict to the royal justices based on this knowledge. The trial-by-jury system employed by Henry II, though only an embryonic form, reflected society's growing understanding that verdicts based on personal knowledge of a dispute were more reliable than verdicts based on ordeals of freezing water and contests of brawn and agility.\r\n" + 
			"Henry II also made the law more impersonal and less vindictive. In 1166, the Assize of Clarendon prohibited the prosecution of anyone who had not first been accused by a \"presenting jury\" of 12 to 16 men from the community in which the crime occurred. The presenting jury fore-shadowed the modern Grand Jury as an accusatory body that identified persons for prosecution but made no determination as to guilt or innocence. The presenting jury was seen as a more neutral and detached alternative to the system it replaced, which required the alleged victims, some of whom were waging a personal vendetta against the accused person, to identify alleged criminals for prosecution.\r\n" + 
			"The writ de odio et atia provided additional safeguards for defendants wrongfully accused of criminal activity, by permitting the defendant to appeal legal issues to the King's Court in cases where the complainant was proceeding out of spite or hatred. This writ of appeal was an early precursor to the modern appellate system in the United States, which similarly permits parties to appeal legal issues they believe did not receive appropriate consideration at the trial level.\r\n" + 
			"The presenting jury and writ of appeal underpin two beliefs that have been crucial to the development of the English and U.S. systems of justice. The first is the belief that a wrongfully accused person is no less a victim than is the target of civil or criminal malfeasance. The second is the belief that the legal system must provide an impartial forum for seeking the truth in disputed legal claims. These two beliefs paved the way for an assortment of procedural and evidentiary protections that have evolved to protect innocent persons from being unjustly convicted in criminal cases, and to keep prejudices from biasing judges and jurors in civil cases.\r\n" + 
			"However, the English monarchy did not centralize its power without cost. Frequently, English rulers abused their enlarged power to such an extent that they met with popular resistance. One of the earliest such confrontations occurred in 1215, and produced the first great charter of constitutional liberties, the Magna Charta. The Magna Charta can best be understood as a peace treaty between three rival jurisdictions of political and legal power: the Crown, the church, and the barons.\r\n" + 
			"In the thirteenth century, the king's system of justice competed for influence with ecclesiastical and manorial courts. The ecclesiastical courts were run by the Catholic Church, with the pope presiding as the spiritual head in Rome. Manorial courts were run by barons, who were powerful men holding large parcels of land from the king, known as manors. Each baron, as lord of his manor, retained jurisdiction over most legal matters arising among his tenants, also called vassals, who agreed to work on the land in exchange for shelter and security. The jurisdictions of the Crown, the church, and the barons overlapped and each depended on the others for support.\r\n" + 
			"The tyranny of King John (1199–1216) alienated the church and the barons, converting them into adversaries of the Crown. John was excommunicated by the pope, church services and sacraments were suspended in England, and the barons renounced homage to the Crown. Spearheaded by Stephen Langton, archbishop of Canterbury, the barons confronted King John on the battlefield at Runnymede, where they won recognition for certain fundamental liberties contained in the 63 clauses that make up the Magna Charta.\r\n" + 
			"The Magna Charta granted the church freedom from royal interference except in a limited number of circumstances, establishing in nascent form the separation of church and state. The Great Charter required that all fines bear some relationship to the seriousness of the offense for which they were imposed, establishing the principle of proportionality between punishment and crime, which the U.S. Supreme Court still applies under the Cruel and Unusual Punishment Clause of the Eighth Amendment to the U.S. Constitution.\r\n" + 
			"Most important the Magna Charta prohibited any \"free man\" from being \"imprisoned, or disseised, … or exiled, … except by the lawful judgment of his peers, or by the law of the land\" (ch. 39). The phrase \"law of the land\" was later equated with \"due process\" in the American colonies and received constitutional recognition in the Fifth and Fourteenth Amendments to the U.S. Constitution. The Supreme Court has described due process as the \"most comprehensive of liberties\" guaranteed in the Constitution (rochin v. california, 342 U.S. 165, 72 S. Ct. 205, 96 L. Ed. 183 [1952]), and has relied on the due process clause of the Fourteenth Amendment to make most of the freedoms contained in the Bill of Rights applicable to the states.\r\n" + 
			"Fifty years after Magna Charta, Parliament was created to serve as an additional check on the Arbitrary power of the monarchy. In 1265, Parliament was a very small body, consisting of two knights from each shire, two citizens from each city, and two burgesses from each borough. By the fourteenth century, Parliament was being summoned to advise the monarch, vote on financial matters, and supervise the excesses of local officials. Representatives for the barons, later known collectively as the House of Lords, wielded more power than did representatives for the commoners, later known collectively as the House of Commons, who were summoned merely to assent to royal will.\r\n" + 
			"It was not long, however, before the Commons realized that its approval carried a measure of authority. In 1309, the Commons granted a subsidy to King Edward II (1307–27) on condition that he redress its grievances. During the reign of Edward III (1327–77), Parliament asserted three claims that would be echoed with minor variation in the American colonies: taxes assessed without approval from both houses of Parliament were void, legislation passed by only one house of Parliament lacked legal effect, and the Commons reserved the right to investigate and remedy any abuses by the royal administration. A century later, during the reign of Henry VIII (1509–47), the Commons asserted the power of the purse, arguing that all money bills must originate in its house.\r\n" + 
			"These claims, although fairly innocuous when originally asserted by the Commons, were interpreted by subsequent Parliaments to mean that no one could rule without the consent of Parliament, and royal officials who abused their power, including the ruler, could be impeached and removed from office. When the English civil war known as the War of the Roses (1455–85) substantially depleted the ranks of the barons, the voice of the Commons grew louder as the representatives of the commoners were left to fend almost for themselves against a monarchical power that, culminating in the reign of James I (1603–25), claimed to be divine in origin and absolute in nature.\r\n" + 
			"The struggles between Parliament and the crown for authority over England in the seventeenth century were a prelude to the struggles between Parliament and the colonists for control over the American colonies in the eighteenth century. The monarchy maintained that its power to govern England derived directly from God and thus overrode any earthly power, including that of Parliament and common law. Parliament, on the other hand, maintained that \"the people, under God, were the source of all just power, and that Parliament represented the people.\"Parliament and the monarchy waged battle on three fronts: military, political, and legal. The military struggle for power began in 1642 when England again erupted into civil war. The political battles constituted a series of muscle-flexing exercises conducted by Parliament and the monarchy. The Commons impeached several of the king's top advisers and demanded redress of the grievances it summarized in the 1628 Petition of Right. The monarchy, in turn, dismissed Parliament on a number of occasions, and attempted to govern without requesting revenue from the Commons.\r\n" + 
			"These political struggles came to a crescendo when King Charles I (1625–49) and Thomas Wentworth, the commander of the king's largest army, were tried, convicted, and executed for subverting Parliament and the Rule of Law. The indictment against the king reads much like the Declaration of Independence:\r\n" + 
			" Whereas it is notorious, That Charles Stuart, the now king of England, not content with those many encroachments which his predecessors had made upon the people in their rights and freedoms, hath had a wicked design totally to subvert the ancient and fundamental laws and liberties of this nation, and in their place to introduce an arbitrary and tyrannical government; and that besides all other evil ways and means to bring this design to pass, he hath prosecuted with fire and sword, levied and maintained a cruel war in the land against the parliament and kingdom, whereby the country hath been miserably wasted, the public treasure exhausted, trade decayed, thousands of people murdered, and infinite other mischiefs committed. During the sentencing phase of the trial, the president of the High Court of Justice instructed the king, in language that resonates through the U.S. Constitution, \"[T]he Law is your Superior,\" and the only thing superior to the law is the \"Parent or Author of Law, [which] is the people of England.\"In 1689, Parliament achieved victory in its constitutional struggle with the monarchy when William and Mary (1689–1702) agreed to govern England as king and queen subject to a bill of rights. This English Bill of Rights, a forerunner to the U.S. Bill of Rights, which was submitted to Congress exactly one hundred years later, declares that the monarchy's \"pretended power of suspending of laws or the execution of laws by regal authority without consent of Parliament is illegal.\" It also guarantees the right of each English subject to \"petition the king\" for redress of grievances, and acknowledges Parliament's role in \"amending, strengthening, and preserving … the laws\" of the country.\r\n" + 
			"Although the English Bill of Rights ended England's seventeenth-century constitutional struggle between Parliament and the monarchy, America's eighteenth-century constitutional struggle with these two branches of government had not yet begun. By 1765, the pendulum of power had swung fully toward Parliament, prompting eminent English jurist Sir William Blackstone to write that \"[s]o long as the English constitution lasts … the power of Parliament\" is \"absolute,\" \"despotic,\" and \"without control.\" Because England had no written constitution that constrained the legislative power of Parliament, \"every act of Parliament was in a sense part of the [English] constitution, and all law … was thus constitutional.\"The American colonists soon discovered that a legislative despot was just as tyrannical as a monarchical despot. The U.S. Constitution put an end to the notion of absolute power resting with any one sovereign, by separating the powers of government into three branches—executive, legislative, and judicial—and carefully delegating the powers of each. Although these safeguards against government-run-amok were the product of the violent American Revolution, they allowed for the tranquil and uneventful Integration of many ordinary English legal principles into the U.S. system of justice, including early Bankruptcy and Welfare laws during the nineteenth century.";
}
